/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Customer;
import Model.DeliveryPackage;
import Model.Product;
import javax.swing.JOptionPane;
/**
 *
 * @author zhengzhang
 */
public class CreateJPanel extends javax.swing.JPanel {

    private DeliveryPackage delPackage;
    private Boolean validate = false;
    /**
     * Creates new form CreateJPanel
     */
    public CreateJPanel() {
        initComponents();
    }
    
    CreateJPanel (DeliveryPackage deliveryPackage){
        initComponents();
        this.delPackage = deliveryPackage;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        packageId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        packageWeight = new javax.swing.JTextField();
        productId1 = new javax.swing.JTextField();
        productName1 = new javax.swing.JTextField();
        productPrice1 = new javax.swing.JTextField();
        customerId1 = new javax.swing.JTextField();
        customerName1 = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        save_product = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Package ID");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));
        add(packageId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 80, -1));

        jLabel2.setText("Package Weight");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel3.setText("Product ID");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel4.setText("Product Name");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLabel5.setText("Product Price");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel6.setText("Customer ID");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        jLabel7.setText("Customer Name");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, -1));
        add(packageWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 80, -1));

        productId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productId1ActionPerformed(evt);
            }
        });
        add(productId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 80, -1));
        add(productName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 80, -1));
        add(productPrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 80, -1));
        add(customerId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 60, -1));

        customerName1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                customerName1FocusLost(evt);
            }
        });
        customerName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerName1ActionPerformed(evt);
            }
        });
        add(customerName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 60, -1));

        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 150, 210, -1));

        save_product.setText("SAVE PRODUCT");
        save_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_productActionPerformed(evt);
            }
        });
        add(save_product, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        
        //get the data
        String id = packageId.getText();
        String weight = packageWeight.getText();
        String customerId = customerId1.getText();
        String customerName = customerName1.getText();
        
        //store the data
        this.delPackage.setPackageId(Integer.valueOf(id));
        this.delPackage.setPackageWeight(Double.valueOf(weight));
        
        Customer customer = this.delPackage.getCustomer();
        customer.setCustomerId(Integer.valueOf(customerId));
        customer.setFullName(customerName);
        
        if (validate){
            JOptionPane.showMessageDialog(null,"Please fill all the blank field!");
        }else{
             JOptionPane.showMessageDialog(null,"Saved");
        }   
        
    }//GEN-LAST:event_saveActionPerformed

    
    private void productId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productId1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_productId1ActionPerformed

    private void save_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_productActionPerformed
        // TODO add your handling code here:
    String productId = productId1.getText();
    String productName = productName1.getText();
    String productPrice =productPrice1.getText();
    
    Product product = this.delPackage.createProduct(Integer.valueOf(productId),Double.valueOf(productPrice),productName);
    JOptionPane.showMessageDialog(null,"Product Added");
    }//GEN-LAST:event_save_productActionPerformed

    private void customerName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerName1ActionPerformed

    private void customerName1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customerName1FocusLost
        // TODO add your handling code here:
       String name = customerName1.getText();
       
       if(name.isEmpty()){
           this.validate =true;
       }else{
           this.validate=false;
       }
    }//GEN-LAST:event_customerName1FocusLost

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField customerId1;
    private javax.swing.JTextField customerName1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField packageId;
    private javax.swing.JTextField packageWeight;
    private javax.swing.JTextField productId1;
    private javax.swing.JTextField productName1;
    private javax.swing.JTextField productPrice1;
    private javax.swing.JButton save;
    private javax.swing.JButton save_product;
    // End of variables declaration//GEN-END:variables
}
