/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.ManegerWorkArea;

import Business.Business;
import Business.UserAccount;
import Business.UserAccountDirectory;
import Restaurant.DeliveryAgent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zhengzhang
 */
public class DeliveryAgentManagementJpanel extends javax.swing.JPanel {

    /**
     * Creates new form DeliveryAgentManagementJpanel
     */
    private UserAccount useraccount;
    private Business business;
    DefaultTableModel tableModel;

    public DeliveryAgentManagementJpanel() {
        initComponents();
    }
    
  DeliveryAgentManagementJpanel(Business business, UserAccount account ){
          initComponents();
          this.business=business;
          this.useraccount=useraccount;
          this.tableModel=(DefaultTableModel)jTable1.getModel();
          populate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldusername1 = new javax.swing.JTextField();
        fieldPassword1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        addAgentBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        addAgentBtn.setText("Add agent");
        addAgentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAgentBtnActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Username", "Password"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addAgentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fieldusername1)
                    .addComponent(fieldPassword1)
                    .addComponent(jTextField3)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fieldusername1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fieldPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(addAgentBtn)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addAgentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAgentBtnActionPerformed
        // TODO add your handling code here:
        UserAccountDirectory ua= this.business.getUseraccountDirectory();
        if (ua.accountExists(fieldusername1.getText(),fieldPassword1.getText(),"agent")){
            JOptionPane.showMessageDialog(null,"Sorry credentials are taken.");
        } else{
                    UserAccount user = this.business.getUseraccountDirectory().createUserAccount(fieldusername1.getText(),fieldPassword1.getText(),"agent");
                    this.business.getDeliveryAgentDirectory().createAgent(user.getAccountId(), fieldusername1.getText(),fieldPassword1.getText());
                    populate();
                    }
    }//GEN-LAST:event_addAgentBtnActionPerformed
    public void populate() {
        tableModel.setRowCount(0);
        for (DeliveryAgent d:this.business.getDeliveryAgentDirectory().getAgentlist()){
            UserAccount u = this.business.getUseraccountDirectory().findById(d.getPersonID());
            
            Object[] row= new Object[4];
            row[0]=d.getPersonID();
            row[1]=d.getName();
            row[2]=u.getUsername();
            row[3]=u.getPassword();
            
            tableModel.addRow(row);
            
        }
    
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAgentBtn;
    private javax.swing.JTextField fieldPassword1;
    private javax.swing.JTextField fieldusername1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
