/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;


import Model.Address;
import Model.ContactInformation;
import Model.Person;
import javax.swing.JOptionPane;

/**
 *
 * @author zhengzhang
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public Person person;
    public MainJFrame() {
      
        initComponents();
        this.person = new Person();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        ViewJpanel = new javax.swing.JPanel();
        ViewFirstName = new javax.swing.JLabel();
        ViewPStreet = new javax.swing.JLabel();
        ViewLastName = new javax.swing.JLabel();
        ViewCollege = new javax.swing.JLabel();
        ViewNUID = new javax.swing.JLabel();
        ViewPersonalPhone = new javax.swing.JLabel();
        ViewPersonalEmail = new javax.swing.JLabel();
        ViewPAPT = new javax.swing.JLabel();
        ViewPCity = new javax.swing.JLabel();
        ViewPZipCode = new javax.swing.JLabel();
        ViewOfficePhone = new javax.swing.JLabel();
        ViewOfficeEmail = new javax.swing.JLabel();
        ViewCStreet = new javax.swing.JLabel();
        ViewCAptNO = new javax.swing.JLabel();
        ViewCCity = new javax.swing.JLabel();
        ViewCZipCode = new javax.swing.JLabel();
        UsersFromPanel = new javax.swing.JPanel();
        fieldFirstName = new javax.swing.JTextField();
        fieldCStreet = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fieldLastName = new javax.swing.JTextField();
        fieldCollegeName = new javax.swing.JTextField();
        fieldID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        daadf = new javax.swing.JLabel();
        fieldPersonalPhone = new javax.swing.JTextField();
        fieldPersonalEmail = new javax.swing.JTextField();
        fieldCAptNo = new javax.swing.JTextField();
        fieldCCity = new javax.swing.JTextField();
        fieldCZipCode = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        faf = new javax.swing.JLabel();
        fmap = new javax.swing.JLabel();
        fieldOfficePhone = new javax.swing.JTextField();
        fieldOfficeEmail = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        fieldPStreet = new javax.swing.JTextField();
        fieldPAptNo = new javax.swing.JTextField();
        fieldPCity = new javax.swing.JTextField();
        fieldPZipCode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ViewJpanel.setBackground(new java.awt.Color(204, 255, 204));

        ViewFirstName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ViewFirstName.setText("First name");

        ViewPStreet.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ViewPStreet.setText("Permanent Street");

        ViewLastName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ViewLastName.setText("Last name");

        ViewCollege.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ViewCollege.setText("College name");

        ViewNUID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ViewNUID.setText("NU ID");

        ViewPersonalPhone.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ViewPersonalPhone.setText("Personal Phone");

        ViewPersonalEmail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ViewPersonalEmail.setText("Personal E-mail");

        ViewPAPT.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ViewPAPT.setText("Permanent Apt No.");

        ViewPCity.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ViewPCity.setText("Permanent City");

        ViewPZipCode.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ViewPZipCode.setText("Permanent ZipCode");

        ViewOfficePhone.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ViewOfficePhone.setText("Office Phone");

        ViewOfficeEmail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ViewOfficeEmail.setText("Office E-mail");

        ViewCStreet.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ViewCStreet.setText("Current Street");

        ViewCAptNO.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ViewCAptNO.setText("Current Apt No.");

        ViewCCity.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ViewCCity.setText("Current City");

        ViewCZipCode.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ViewCZipCode.setText("Current ZipCode");

        javax.swing.GroupLayout ViewJpanelLayout = new javax.swing.GroupLayout(ViewJpanel);
        ViewJpanel.setLayout(ViewJpanelLayout);
        ViewJpanelLayout.setHorizontalGroup(
            ViewJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewJpanelLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(ViewJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ViewCZipCode)
                    .addComponent(ViewCCity)
                    .addComponent(ViewCAptNO)
                    .addComponent(ViewCStreet)
                    .addComponent(ViewOfficeEmail)
                    .addGroup(ViewJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ViewLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ViewFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ViewNUID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ViewCollege, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ViewPersonalPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ViewPersonalEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ViewPStreet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ViewPAPT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ViewPCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ViewPZipCode, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                    .addComponent(ViewOfficePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        ViewJpanelLayout.setVerticalGroup(
            ViewJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewJpanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(ViewFirstName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ViewLastName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ViewCollege)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ViewNUID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ViewPersonalPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ViewPersonalEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ViewOfficePhone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ViewOfficeEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ViewCStreet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ViewCAptNO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ViewCCity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ViewCZipCode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ViewPStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ViewPAPT, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ViewPCity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ViewPZipCode)
                .addContainerGap())
        );

        jSplitPane1.setRightComponent(ViewJpanel);

        UsersFromPanel.setBackground(new java.awt.Color(204, 204, 255));

        fieldFirstName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFirstNameActionPerformed(evt);
            }
        });

        fieldCStreet.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldCStreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCStreetActionPerformed(evt);
            }
        });

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("First name");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Current Street");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Last name");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("College name");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("NU ID");

        fieldLastName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldLastNameActionPerformed(evt);
            }
        });

        fieldCollegeName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldCollegeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCollegeNameActionPerformed(evt);
            }
        });

        fieldID.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIDActionPerformed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Personal Phone");

        daadf.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        daadf.setText("Personal E-mail");

        fieldPersonalPhone.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldPersonalPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPersonalPhoneActionPerformed(evt);
            }
        });

        fieldPersonalEmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        fieldCAptNo.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        fieldCCity.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldCCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCCityActionPerformed(evt);
            }
        });

        fieldCZipCode.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldCZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCZipCodeActionPerformed(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Current Apt No.");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Current City/State");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Current ZipCode");

        faf.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        faf.setText("Office Phone");

        fmap.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fmap.setText("Office E-mail");

        fieldOfficePhone.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        fieldOfficeEmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldOfficeEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldOfficeEmailActionPerformed(evt);
            }
        });

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Permanent Street");

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Permanent Apt No.");

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Permanent City/State");

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Permanent ZipCode");

        fieldPStreet.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldPStreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPStreetActionPerformed(evt);
            }
        });

        fieldPAptNo.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        fieldPCity.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldPCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPCityActionPerformed(evt);
            }
        });

        fieldPZipCode.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        javax.swing.GroupLayout UsersFromPanelLayout = new javax.swing.GroupLayout(UsersFromPanel);
        UsersFromPanel.setLayout(UsersFromPanelLayout);
        UsersFromPanelLayout.setHorizontalGroup(
            UsersFromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsersFromPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(UsersFromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UsersFromPanelLayout.createSequentialGroup()
                        .addGroup(UsersFromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UsersFromPanelLayout.createSequentialGroup()
                                .addComponent(fmap, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))
                            .addGroup(UsersFromPanelLayout.createSequentialGroup()
                                .addGroup(UsersFromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(UsersFromPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel3))
                                    .addGroup(UsersFromPanelLayout.createSequentialGroup()
                                        .addGroup(UsersFromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(UsersFromPanelLayout.createSequentialGroup()
                                        .addComponent(daadf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(30, 30, 30)))
                                .addGap(10, 10, 10)))
                        .addGroup(UsersFromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldOfficeEmail)
                            .addComponent(fieldPersonalPhone, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldCollegeName)
                            .addComponent(fieldID)
                            .addComponent(fieldLastName)
                            .addComponent(fieldFirstName)
                            .addComponent(fieldPersonalEmail)))
                    .addGroup(UsersFromPanelLayout.createSequentialGroup()
                        .addComponent(faf, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(fieldOfficePhone))
                    .addGroup(UsersFromPanelLayout.createSequentialGroup()
                        .addGroup(UsersFromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UsersFromPanelLayout.createSequentialGroup()
                                .addGroup(UsersFromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)))
                        .addGroup(UsersFromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(UsersFromPanelLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(UsersFromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldPAptNo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fieldPStreet)))
                            .addGroup(UsersFromPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(UsersFromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldPZipCode, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fieldPCity)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UsersFromPanelLayout.createSequentialGroup()
                        .addGroup(UsersFromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(UsersFromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldCStreet, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldCAptNo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldCZipCode, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldCCity))))
                .addGap(17, 17, 17))
            .addGroup(UsersFromPanelLayout.createSequentialGroup()
                .addGap(339, 339, 339)
                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(349, Short.MAX_VALUE))
        );
        UsersFromPanelLayout.setVerticalGroup(
            UsersFromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsersFromPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(UsersFromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UsersFromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UsersFromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldCollegeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(UsersFromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UsersFromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldPersonalPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(6, 6, 6)
                .addGroup(UsersFromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(daadf)
                    .addComponent(fieldPersonalEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UsersFromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(faf)
                    .addComponent(fieldOfficePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UsersFromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fmap, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldOfficeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UsersFromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UsersFromPanelLayout.createSequentialGroup()
                        .addGroup(UsersFromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(fieldCStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(UsersFromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(fieldCAptNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UsersFromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldCCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UsersFromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(fieldCZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UsersFromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldPStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UsersFromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(fieldPAptNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UsersFromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldPCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UsersFromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(fieldPZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(UsersFromPanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        String fname = fieldFirstName.getText();
        String lname = fieldLastName.getText();
        String nuid = fieldID.getText();
        String collegeName = fieldCollegeName.getText();
        
        String cstreet = fieldCStreet.getText();
        String pstreet = fieldPStreet.getText();
        String cAptNo = fieldCAptNo.getText();
        String pAptNo = fieldPAptNo.getText();
        String cCity = fieldCCity.getText();
        String pCity = fieldPCity.getText();
        String cZipCode = fieldCZipCode.getText();
        String pZipCode = fieldPZipCode.getText();
        
        String officePhone = fieldOfficePhone.getText();
        String officeEmail = fieldOfficeEmail.getText();
        String personalPhone = fieldPersonalPhone.getText();
        String personalEmail = fieldPersonalEmail.getText();
        
        
        
        this.person.setFirstName(fname);
        this.person.setLastName(lname);
        this.person.setCollegeName(collegeName);
        this.person.setNUID(nuid);
        
        
        Address address = this.person.getAddress();
        address.setCstreetName(cstreet);
        address.setPstreetName(pstreet);
        address.setcAptNo(cAptNo);
        address.setpAptNo(pAptNo);
        address.setcCityState(cCity);
        address.setpCityState(pCity);
        address.setcZipCode(cZipCode);
        address.setpZipCode(pZipCode);
        
        ContactInformation contactInformation = this.person.getContactInformation();
        contactInformation.setOfficeEmail(officeEmail);
        contactInformation.setOfficePhone(officePhone);
        contactInformation.setPersonalPhone(personalPhone);
        contactInformation.setPersonalEmail(personalEmail);
                
        JOptionPane.showConfirmDialog(null,"Saved");
        display();
    }
        
      private void display(){
        
        ViewFirstName.setText(this.person.getFirstName());
        ViewLastName.setText(this.person.getLastName());
        ViewNUID.setText(this.person.getNUID());
        ViewCollege.setText(this.person.getCollegeName());
        
        ViewCStreet.setText(this.person.getAddress().getCstreetName());
        ViewPStreet.setText(this.person.getAddress().getPstreetName());
        ViewPZipCode.setText(this.person.getAddress().getpZipCode());
        ViewCZipCode.setText(this.person.getAddress().getcZipCode());
        ViewCCity.setText(this.person.getAddress().getcCityState());
        ViewPCity.setText(this.person.getAddress().getpCityState());
        ViewCAptNO.setText(this.person.getAddress().getcAptNo());
        ViewPAPT.setText(this.person.getAddress().getpAptNo());
        
        ViewPersonalEmail.setText(this.person.getContactInformation().getPersonalEmail());
        ViewPersonalPhone.setText(this.person.getContactInformation().getPersonalPhone());
        ViewOfficeEmail.setText(this.person.getContactInformation().getOfficeEmail());
        ViewOfficePhone.setText(this.person.getContactInformation().getOfficePhone());
    }//GEN-LAST:event_saveActionPerformed

    private void fieldFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldFirstNameActionPerformed

    private void fieldCStreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCStreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCStreetActionPerformed

    private void fieldLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldLastNameActionPerformed

    private void fieldCollegeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCollegeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCollegeNameActionPerformed

    private void fieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIDActionPerformed

    private void fieldPersonalPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPersonalPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPersonalPhoneActionPerformed

    private void fieldCCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCCityActionPerformed

    private void fieldCZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCZipCodeActionPerformed

    private void fieldOfficeEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldOfficeEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldOfficeEmailActionPerformed

    private void fieldPStreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPStreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPStreetActionPerformed

    private void fieldPCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPCityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UsersFromPanel;
    private javax.swing.JLabel ViewCAptNO;
    private javax.swing.JLabel ViewCCity;
    private javax.swing.JLabel ViewCStreet;
    private javax.swing.JLabel ViewCZipCode;
    private javax.swing.JLabel ViewCollege;
    private javax.swing.JLabel ViewFirstName;
    private javax.swing.JPanel ViewJpanel;
    private javax.swing.JLabel ViewLastName;
    private javax.swing.JLabel ViewNUID;
    private javax.swing.JLabel ViewOfficeEmail;
    private javax.swing.JLabel ViewOfficePhone;
    private javax.swing.JLabel ViewPAPT;
    private javax.swing.JLabel ViewPCity;
    private javax.swing.JLabel ViewPStreet;
    private javax.swing.JLabel ViewPZipCode;
    private javax.swing.JLabel ViewPersonalEmail;
    private javax.swing.JLabel ViewPersonalPhone;
    private javax.swing.JLabel daadf;
    private javax.swing.JLabel faf;
    private javax.swing.JTextField fieldCAptNo;
    private javax.swing.JTextField fieldCCity;
    private javax.swing.JTextField fieldCStreet;
    private javax.swing.JTextField fieldCZipCode;
    private javax.swing.JTextField fieldCollegeName;
    private javax.swing.JTextField fieldFirstName;
    private javax.swing.JTextField fieldID;
    private javax.swing.JTextField fieldLastName;
    private javax.swing.JTextField fieldOfficeEmail;
    private javax.swing.JTextField fieldOfficePhone;
    private javax.swing.JTextField fieldPAptNo;
    private javax.swing.JTextField fieldPCity;
    private javax.swing.JTextField fieldPStreet;
    private javax.swing.JTextField fieldPZipCode;
    private javax.swing.JTextField fieldPersonalEmail;
    private javax.swing.JTextField fieldPersonalPhone;
    private javax.swing.JLabel fmap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
