/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package UI;

import Model.Application;
import Model.VitalSignHistory;
import javax.swing.JOptionPane;

/**
 *
 * @author zhengzhang
 */
public class CreateJPanel extends javax.swing.JPanel {

    
    Application application;
    /** Creates new form CreateJPanel */
    public CreateJPanel() {
        initComponents();
    }

    CreateJPanel(Application application) {
         initComponents();
         this.application=application;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bloodPressureTextField = new javax.swing.JTextField();
        IDTextField = new javax.swing.JTextField();
        TemperatureTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setText("CREATE A  VITAL SIGN");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 179, 37));

        jLabel2.setText("ID");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 70, 20));
        add(bloodPressureTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 130, -1));
        add(IDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 130, -1));
        add(TemperatureTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 130, -1));

        jLabel3.setText("Temp.");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jLabel4.setText("Blood Pressure");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jButton1.setText("Add Observation");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 150, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        VitalSignHistory history = this.application.getHistory();
        String id = IDTextField.getText();
        String temp = TemperatureTextField.getText();
        String bp = bloodPressureTextField.getText();
        
        
        history.createObservation(Integer.valueOf(id), Double.valueOf(bp), Double.valueOf(temp));
        
        JOptionPane.showMessageDialog(null, "Added Observation");
    }//GEN-LAST:event_jButton1ActionPerformed

    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDTextField;
    private javax.swing.JTextField TemperatureTextField;
    private javax.swing.JTextField bloodPressureTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

}
